# Generated by Django 4.0.4 on 2022-06-14 08:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=9999)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='video/%y')),
                ('title', models.CharField(max_length=5000)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(max_length=9999)),
                ('category', models.CharField(choices=[('GM', 'Gaming'), ('MV', 'Movies'), ('ED', 'Education'), ('MC', 'Music'), ('TE', 'Technology'), ('NW', 'News'), ('SP', 'Sports'), ('FB', 'Fashion & Beauty')], max_length=16)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
        ),
    ]
