# Generated by Django 4.0.5 on 2022-06-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created_by',
        ),
    ]
