# Generated by Django 4.0 on 2022-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_video_comments_remove_video_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('GM', 'Gaming'), ('MV', 'Movies'), ('ED', 'Education'), ('MC', 'Music'), ('TE', 'Technology'), ('NW', 'News'), ('SP', 'Sports'), ('FB', 'Fashion & Beauty')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='default', max_length=5000),
        ),
    ]
