# Generated by Django 4.0 on 2022-07-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_category_alter_video_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
