# Generated by Django 4.0 on 2022-08-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_remove_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
