# Generated by Django 4.0 on 2022-12-26 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.comment'),
        ),
    ]
